import type { ComparisonPoolPlayer } from "../data/comparisonPool.js";
import { applyVote, initializeRatings } from "./elo.js";
import { rankPlayers } from "./ranking.js";
import type { Player, Ratings } from "./types.js";
export interface DemoSession { players: Player[]; source: ComparisonPoolPlayer[]; ratings: Ratings; comparisons: number; shuffled: ComparisonPoolPlayer[]; pairIndex: number; lastPair?: string; seed?: number; }
export function mapPoolPlayers(players: readonly ComparisonPoolPlayer[]): Player[] { return players.map(p => ({ id:p.id, name:p.name, team:p.teamAbbreviation, position:p.positionGroup })); }
function random(seed?: number): () => number { let state=seed ?? Math.floor(Math.random()*0x7fffffff); return () => { state=(state*1664525+1013904223)>>>0; return state/0x100000000; }; }
function shuffle(players: readonly ComparisonPoolPlayer[], seed?: number): ComparisonPoolPlayer[] { const output=structuredClone([...players]), next=random(seed); for(let i=output.length-1;i>0;i--){const j=Math.floor(next()*(i+1));[output[i],output[j]]=[output[j],output[i]];} return output; }
/** The terminal demo is deliberately memory-only: it exercises integration without collecting or saving anyone's votes. */
export function createDemoSession(pool: readonly ComparisonPoolPlayer[], seed?: number): DemoSession { const players=mapPoolPlayers(pool); return { players, source: structuredClone([...pool]), ratings: initializeRatings(players), comparisons:0, shuffled:shuffle(pool,seed), pairIndex:0, seed }; }
export function vote(session: DemoSession, winnerId:string, loserId:string): { session:DemoSession; before:{winner:number;loser:number}; after:{winner:number;loser:number} } { const before=rankPlayers(session.players,session.ratings); const ranks=(id:string)=>before.findIndex(x=>x.player.id===id)+1; const ratings=applyVote(session.ratings,winnerId,loserId); const after=rankPlayers(session.players,ratings); return { session:{...session,ratings,comparisons:session.comparisons+1},before:{winner:ranks(winnerId),loser:ranks(loserId)},after:{winner:after.findIndex(x=>x.player.id===winnerId)+1,loser:after.findIndex(x=>x.player.id===loserId)+1} }; }
export function skipMatchup(session: DemoSession): DemoSession { return session; }
export function topCompared(session: DemoSession, limit=25) { return rankPlayers(session.players,session.ratings).filter(x=>x.comparisons>0).slice(0,limit); }
export function formatDecimal(value:number): string { return new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(value); }
export function formatPlayer(p: ComparisonPoolPlayer): string { const s=p.currentSeason; const lines=[`${p.name}\n${p.teamName} | ${p.positionGroup}${p.age!==undefined?` | Age ${p.age}`:""}`,"2026", `Minutes: ${(s.minutes??0).toLocaleString()}`]; const stats: Array<[string,number|undefined]>=[["Starts",s.starts],["Goals",s.goals],["Assists",s.assists],["xG",s.xGoals],["xA",s.xAssists],["Goals Added",s.goalsAdded]]; for (const [label,value] of stats) if(value!==undefined) lines.push(`${label}: ${formatDecimal(value)}`); if(p.guaranteedCompensation!==undefined||p.baseSalary!==undefined) lines.push(`Salary: $${(p.guaranteedCompensation??p.baseSalary!).toLocaleString()}`); const r=p.rosterProfile; if(r?.rosterDesignation) lines.push(`Designation: ${r.rosterDesignation}`); if(r?.contractThrough) lines.push(`Contract through: ${r.contractThrough}`); if(r?.optionYears?.length) lines.push(`Option years: ${r.optionYears.join(", ")}`); return lines.join("\n"); }
/** A temporary shuffled sequence prevents adjacent pairs sharing a player; it is not the future balanced scheduler. */
export function nextPair(session: DemoSession): { pair:[ComparisonPoolPlayer,ComparisonPoolPlayer]; session:DemoSession } { if(session.source.length<2) throw new Error("At least two pool players are required"); let shuffled=session.shuffled,index=session.pairIndex; if(index+1>=shuffled.length){const seed=(session.seed ?? 0)+session.comparisons+1; shuffled=shuffle(session.source,seed); index=0; const candidate=[shuffled[0].id,shuffled[1].id].sort().join(":"); if(candidate===session.lastPair&&shuffled.length>2)[shuffled[1],shuffled[2]]=[shuffled[2],shuffled[1]]; } const pair:[ComparisonPoolPlayer,ComparisonPoolPlayer]=[shuffled[index],shuffled[index+1]]; return {pair,session:{...session,shuffled,pairIndex:index+2,lastPair:[pair[0].id,pair[1].id].sort().join(":")}}; }
