import { describe, expect, it } from "vitest";
import { designationSelectionReason, eligible, participationScore, selectComparisonPool, validateComparisonPool, type SelectionReason } from "../src/data/comparisonPool.js";
import type { PlayerDataset, StaticPlayer } from "../src/data/types.js";
const p=(id:string, changes:Partial<StaticPlayer>={}):StaticPlayer=>({id,name:id,teamId:"t",teamName:"Team",teamAbbreviation:"T",positionGroup:"MID",currentSeason:{season:2026,minutes:1},...changes});
const dataset=(players:StaticPlayer[]):PlayerDataset=>({schemaVersion:2,dataVersion:"test",competition:"MLS",season:2026,previousSeason:2025,generatedAt:"2026-01-01T00:00:00.000Z",sources:[],players}); const none={schemaVersion:1 as const,include:[],exclude:[]};
describe("comparison-pool rules",()=>{
 it("accepts current minutes or snapshot-backed prior minutes only",()=>{expect(eligible(p("now"))).toBe(true);expect(eligible(p("old",{currentSeason:{season:2026},previousSeason:{season:2025,minutes:1},rosterProfile:{snapshotDate:"2026-02-26",listedInRosterSnapshot:true,activeAtRosterSnapshot:false,snapshotTeamId:"t",snapshotTeamName:"Team"}}))).toBe(true);expect(eligible(p("no",{currentSeason:{season:2026},previousSeason:{season:2025,minutes:1}}))).toBe(false);});
 it("weights previous minutes by one half",()=>expect(participationScore(p("a",{currentSeason:{season:2026,minutes:10},previousSeason:{season:2025,minutes:100}}))).toBe(60));
 it("takes five outfielders and one goalkeeper per team",()=>{const players=[...Array.from({length:7},(_,i)=>p(`m${i}`,{currentSeason:{season:2026,minutes:100-i}})),p("g1",{positionGroup:"GK",currentSeason:{season:2026,minutes:1}}),p("g2",{positionGroup:"GK",currentSeason:{season:2026,minutes:2}})];const pool=selectComparisonPool(dataset(players),none);expect(pool.players.filter(x=>x.positionGroup!=="GK")).toHaveLength(5);expect(pool.players.filter(x=>x.positionGroup==="GK").map(x=>x.id)).toEqual(["g2"]);});
 it("uses deterministic participation tie-breakers",()=>{const a=p("a",{currentSeason:{season:2026,minutes:20}}),b=p("b",{currentSeason:{season:2026,minutes:20}});expect(selectComparisonPool(dataset([b,a]),none).players.map(x=>x.id)).toEqual(["a","b"]);});
 it("maps only exact observed DP and U22 labels",()=>{expect(designationSelectionReason("Designated Player")).toBe("designated-player");expect(designationSelectionReason("U22 Initiative")).toBe("u22-initiative");expect(designationSelectionReason("TAM Player")).toBeUndefined();});
 it("adds DP, U22, and five-goal-contribution players outside base selection",()=>{const base=Array.from({length:6},(_,i)=>p(`b${i}`,{currentSeason:{season:2026,minutes:100-i}}));const dp=p("dp",{currentSeason:{season:2026,minutes:1},rosterProfile:{snapshotDate:"2026-02-26",listedInRosterSnapshot:true,activeAtRosterSnapshot:true,snapshotTeamId:"t",snapshotTeamName:"Team",rosterDesignation:"Designated Player"}}),u22=p("u22",{currentSeason:{season:2026,minutes:1},rosterProfile:{snapshotDate:"2026-02-26",listedInRosterSnapshot:true,activeAtRosterSnapshot:true,snapshotTeamId:"t",snapshotTeamName:"Team",rosterDesignation:"U22 Initiative"}}),goal=p("goal",{currentSeason:{season:2026,minutes:1,goals:3,assists:2}});const ids=selectComparisonPool(dataset([...base,dp,u22,goal]),none).players.map(x=>x.id);expect(ids).toEqual(expect.arrayContaining(["dp","u22","goal"]));});
 it("does not add four goal contributions",()=>{const player=p("four",{currentSeason:{season:2026,minutes:1,goals:2,assists:2}});expect(selectComparisonPool(dataset([player]),none).players[0].selectionReasons).not.toContain("current-season-five-goal-contributions");});
 it("merges sorted reasons and honors manual exclusion precedence",()=>{const player=p("x",{currentSeason:{season:2026,minutes:1,goals:5},rosterProfile:{snapshotDate:"2026-02-26",listedInRosterSnapshot:true,activeAtRosterSnapshot:true,snapshotTeamId:"t",snapshotTeamName:"Team",rosterDesignation:"Designated Player"}});expect(selectComparisonPool(dataset([player]),{schemaVersion:1,include:[{playerId:"x",reason:"r",sourceNote:"n"}],exclude:[]}).players[0].selectionReasons).toEqual(["team-outfield-selection","designated-player","current-season-five-goal-contributions","manual-inclusion"]);expect(()=>selectComparisonPool(dataset([player]),{schemaVersion:1,include:[{playerId:"x",reason:"r",sourceNote:"n"}],exclude:[{playerId:"x",reason:"r2",sourceNote:"n2"}]})).toThrow();expect(selectComparisonPool(dataset([player]),{schemaVersion:1,include:[],exclude:[{playerId:"x",reason:"r",sourceNote:"n"}]}).players).toHaveLength(0);});
 it("rejects invalid overrides",()=>{expect(()=>selectComparisonPool(dataset([p("x")]),{schemaVersion:1,include:[{playerId:"none",reason:"r",sourceNote:"n"}],exclude:[]})).toThrow();expect(()=>selectComparisonPool(dataset([p("x")]),{schemaVersion:1,include:[{playerId:"x",reason:"",sourceNote:"n"}],exclude:[]})).toThrow();});
 it("validates pool size and duplicate player IDs",()=>{const players=Array.from({length:150},(_,i)=>p(String(i).padStart(3,"0")));const d=dataset(players);const pool={...selectComparisonPool(d,none),players:players.map(x=>({...x,selectionReasons:["manual-inclusion"] as SelectionReason[]}))};expect(validateComparisonPool(pool,d,none)).toEqual([]);expect(validateComparisonPool({...pool,players:[...pool.players,pool.players[0]]},d,none)).toContain("invalid or duplicate player 000");});
 it("does not mutate the source dataset",()=>{const d=dataset([p("x")]);const before=structuredClone(d);selectComparisonPool(d,none);expect(d).toEqual(before);});
});
